/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <FreeRTOSConfig.h>
#include <stm32f4xx.h>
#include <FreeRTOS.h>
#include <task.h>
#include <types.h>
#include <sys_clock.h>
#include <stm32f446_gpio_driver.h>
#include <stm32f446_can_driver.h>
#include "uart_driver.h"

volatile uint32 u_counterTask1 = 0, u_counterTask2 = 0;
static void GPIO_Config(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

CANx_IndetifierHandle_t CanHhdl;
CANx_RecieveHandle_t CanHndlRecieve;
uint8 u_sendDlc;
uint8 u_Data[8] = {};
uint8 u_retDlc[6];
uint8 u_retData[48];
uint8 size1, size2;
uint8 i;

static void GPIO_Config(void)
{
	/* CAN gpio init */
	GPIO_v_PeripheralClockControl(GPIOB, ENABLE);

	GPIO_PinConfig_t GPIO_PinConfiguration;

	GPIO_PinConfiguration.GPIO_PinNumber = 8u;
	GPIO_PinConfiguration.GPIO_PinMode = ALTERNATE_FUNCTION_MODE;
	GPIO_PinConfiguration.GPIO_PinAltFunMode = AF9;

	GPIO_v_Init(GPIOB, GPIO_PinConfiguration);

	GPIOx_v_GPIOCfgStructClear(&GPIO_PinConfiguration);

	GPIO_PinConfiguration.GPIO_PinNumber = 9u;
	GPIO_PinConfiguration.GPIO_PinMode = ALTERNATE_FUNCTION_MODE;
	GPIO_PinConfiguration.GPIO_PinAltFunMode = AF9;

	GPIO_v_Init(GPIOB, GPIO_PinConfiguration);

	/* UART configuration */
	GPIO_v_PeripheralClockControl(GPIOA, ENABLE);
	//GPIOx_v_GPIOCfgStructClear(&GPIO_PinConfiguration);

	//GPIO_PinConfiguration.GPIO_PinNumber = 2u;
	//GPIO_PinConfiguration.GPIO_PinMode = ALTERNATE_FUNCTION_MODE;
	//GPIO_PinConfiguration.GPIO_PinAltFunMode = AF7;

	//GPIO_v_Init(GPIOB, GPIO_PinConfiguration);

	//GPIOx_v_GPIOCfgStructClear(&GPIO_PinConfiguration);

	//GPIO_PinConfiguration.GPIO_PinNumber = 3u;
	//GPIO_PinConfiguration.GPIO_PinMode = ALTERNATE_FUNCTION_MODE;
	//GPIO_PinConfiguration.GPIO_PinAltFunMode = AF7;

	//GPIO_v_Init(GPIOB, GPIO_PinConfiguration);

    /* For some reason code above is not working, need to debug */
   GPIOA->MODER &= ~((3 << (2 * 2)) | (3 << (3 * 2)));
   GPIOA->MODER |=  (2 << (2 * 2)) | (2 << (3 * 2));

   GPIOA->AFR[0] &= ~((0xF << (4 * 2)) | (0xF << (4 * 3)));
   GPIOA->AFR[0] |=  (7 << (4 * 2)) | (7 << (4 * 3));
}

void vTaskIdle(void *pvParameters)
{
    while (1)
    {
    	u_counterTask1++;
        vTaskDelay(pdMS_TO_TICKS(500));
    }

    vTaskDelete(NULL);
}

void vTaskUartRx(void *pvParameters)
{
    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(500));
    }

    vTaskDelete(NULL);
}

void vTaskUartTx(void *pvParameters)
{
    while (1)
    {
    	UART_Write_Message("Firs message in cycle cycle cycle ...\n", 200);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

    vTaskDelete(NULL);
}

void vTaskComRx(void *pvParameters)
{
    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(500));
    }

    vTaskDelete(NULL);
}

void vTaskComTx(void *pvParameters)
{

	static uint8 j, k = 0, g;

	CanHhdl.remoteTransmissionRequest = 0u;
	CanHhdl.identifierExtension = 1u;
	CanHhdl.identifier = 0x18AE2FE8;

    while (1)
    {
    	if(k == 8)
    	{
    		k = 1;
    	}
    	else
    	{
    		k++;
    	}
    	u_sendDlc = k;
    	CAN_u_TransmitMessage(CAN1, &CanHhdl, u_sendDlc, u_Data);
    	CanHhdl.identifier = 0x18EAF2F1;

    	for(g = 0; g < k; g++)
    	{
    		u_Data[k] = j;
    		j++;
    	}
    	CAN_u_TransmitMessage(CAN1, &CanHhdl, u_sendDlc, u_Data);

    	for(i = 0; i < 2; i++)
    	{
    		CAN_u_RecieveMessage(CAN1, &CanHndlRecieve, &size1, &size2);
    	}
    	vTaskDelay(pdMS_TO_TICKS(1000));
    	u_counterTask2++;
    }

    vTaskDelete(NULL);
}


int main(void)
{
	(void)Sys_v_FrequencyConfig(128u, 4u);
	GPIO_Config();
	CAN_v_Init(CAN1);
	CAN_v_FiltersInit(CAN1);
	UART_v_Init(SystemCoreClock, 115200);
	xTaskCreate(vTaskComTx , "Com Tx task"   , 128, NULL, configMAX_PRIORITIES - 1, NULL);
	xTaskCreate(vTaskComRx , "Com Rx task"   , 128, NULL, configMAX_PRIORITIES - 1, NULL);
	xTaskCreate(vTaskUartTx, "UART Tx task " , 128, NULL, configMAX_PRIORITIES - 2, NULL);
	xTaskCreate(vTaskUartRx, "UART Rx task " , 128, NULL, tskIDLE_PRIORITY + 1, NULL); /* Will be used only for configuration purposes where other tasks will be suspended */
	xTaskCreate(vTaskIdle  , "Idle task "    , 128, NULL, tskIDLE_PRIORITY, NULL);
	vTaskStartScheduler();
    /* Loop forever */
	for(;;);
}
