/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <FreeRTOSConfig.h>
#include <stm32f4xx.h>
#include <FreeRTOS.h>
#include <task.h>
#include <types.h>
#include <sys_clock.h>

volatile uint32 u_counterTask1 = 0, u_counterTask2 = 0;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vCounterTask1(void *pvParameters)
{
    while (1)
    {
    	u_counterTask1++;
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}
void vCounterTask2(void *pvParameters)
{
    while (1)
    {
    	u_counterTask2++;
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

int main(void)
{
	Sys_v_FrequencyConfig(128u, 4u);
	xTaskCreate(vCounterTask1, "Counter 1", 128, NULL, tskIDLE_PRIORITY + 1, NULL);
	xTaskCreate(vCounterTask2, "Counter 2", 128, NULL, tskIDLE_PRIORITY + 1, NULL);
	vTaskStartScheduler();
    /* Loop forever */
	for(;;);
}
